apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-app  # Ensure this matches with the namespace in the base
spec:
  replicas: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-app  # Ensure this is correct for your staging environment as well
spec:
  replicas: 2

